import React from 'react';
import { Head, Link, useForm } from '@inertiajs/react';
import useBackgroundRefresh from '@/hooks/useBackgroundRefresh';
import BPLOLayout from '@/Layouts/BPLOLayout';
import Swal from 'sweetalert2';
import {
    ChevronLeft, Hash, ShieldCheck, Loader2,
    CheckCircle2, Info, Lock, Bike, User,
    Phone, MapPin, Gauge, AlertCircle
} from 'lucide-react';

/**
 * Determine coding day and color scheme based on the last digit of the Sticker Number.
 * Conforms with Nasugbu Municipal Traffic Management Ordinance.
 */
function getCodingSchemeInfo(codingNumber) {
    if (!codingNumber) {
        return { day: 'Unassigned', scheme: 'Standard', colorClass: 'bg-slate-100 text-slate-700 border-slate-200' };
    }
    const clean = String(codingNumber).trim();
    const lastChar = clean.charAt(clean.length - 1);
    const lastDigit = parseInt(lastChar, 10);

    if (isNaN(lastDigit)) {
        return { day: 'Unassigned', scheme: 'Standard', colorClass: 'bg-slate-100 text-slate-700 border-slate-200' };
    }

    switch (lastDigit) {
        case 1:
        case 2:
            return {
                day: 'Monday',
                digits: '1 & 2',
                scheme: 'Blue Scheme',
                badgeClass: 'bg-blue-50 text-blue-700 border-blue-200/80',
                dotClass: 'bg-blue-500'
            };
        case 3:
        case 4:
            return {
                day: 'Tuesday',
                digits: '3 & 4',
                scheme: 'Green Scheme',
                badgeClass: 'bg-emerald-50 text-emerald-700 border-emerald-200/80',
                dotClass: 'bg-emerald-500'
            };
        case 5:
        case 6:
            return {
                day: 'Wednesday',
                digits: '5 & 6',
                scheme: 'Yellow Scheme',
                badgeClass: 'bg-amber-50 text-amber-700 border-amber-200/80',
                dotClass: 'bg-amber-500'
            };
        case 7:
        case 8:
            return {
                day: 'Thursday',
                digits: '7 & 8',
                scheme: 'Purple Scheme',
                badgeClass: 'bg-purple-50 text-purple-700 border-purple-200/80',
                dotClass: 'bg-purple-500'
            };
        case 9:
        case 0:
            return {
                day: 'Friday',
                digits: '9 & 0',
                scheme: 'Red Scheme',
                badgeClass: 'bg-rose-50 text-rose-700 border-rose-200/80',
                dotClass: 'bg-rose-500'
            };
        default:
            return {
                day: 'Monday',
                digits: '1 & 2',
                scheme: 'Blue Scheme',
                badgeClass: 'bg-blue-50 text-blue-700 border-blue-200/80',
                dotClass: 'bg-blue-500'
            };
    }
}

// Shared soft, layered shadow token — matches the elevation language used across the TMO panel
// pages so every dashboard in the product reads as one consistent system.
const CARD_SHADOW = 'shadow-[0_1px_2px_0_rgba(15,23,42,0.04),0_8px_24px_-8px_rgba(15,23,42,0.10)]';

export default function IssueStickerNumber({ application }) {
    const autoGeneratedCodingNumber = application.suggested_coding_number || '';
    const franchiseNumber = application.sticker_number || application.suggested_sticker || '';

    const { data, setData, post, processing, errors } = useForm({
        coding_scheme_number: autoGeneratedCodingNumber,
        sticker_number: franchiseNumber,
    });

    // Background refresh of the application being released — its status can move on the TMO side
    // while this officer types the Sticker/Franchise number. Paused while submitting; useForm is
    // initialised once from the first `application` prop, so typed values are never re-seeded.
    useBackgroundRefresh(['application'], { paused: processing });

    const codingInfo = getCodingSchemeInfo(data.coding_scheme_number);

    const handleFinalize = (e) => {
        if (e) e.preventDefault();

        if (!data.sticker_number || !data.sticker_number.trim()) {
            Swal.fire({
                title: 'Franchise Number Required',
                text: 'Please provide the Franchise Number to be released to the operator.',
                icon: 'warning',
                confirmButtonColor: '#1D2542'
            });
            return;
        }

        Swal.fire({
            title: 'Confirm Franchise Number & Plate Release',
            html: `
                <div class="text-left text-xs text-slate-600 space-y-2 mt-2 p-3.5 bg-slate-50 rounded-xl border border-slate-200/80">
                    <div class="flex justify-between pb-1.5 border-b border-slate-200/60">
                        <span class="text-slate-400 font-bold uppercase tracking-wider text-[10px]">Tricycle Owner:</span>
                        <span class="font-bold text-slate-800">${application.operator}</span>
                    </div>
                    <div class="flex justify-between pb-1.5 border-b border-slate-200/60">
                        <span class="text-slate-400 font-bold uppercase tracking-wider text-[10px]">Sticker Number:</span>
                        <span class="font-mono font-bold text-[#1D2542] text-sm">${data.coding_scheme_number}</span>
                    </div>
                    <div class="flex justify-between pb-1.5 border-b border-slate-200/60">
                        <span class="text-slate-400 font-bold uppercase tracking-wider text-[10px]">Franchise Number:</span>
                        <span class="font-mono font-bold text-slate-800">${data.sticker_number}</span>
                    </div>
                    <div class="flex justify-between pt-0.5">
                        <span class="text-slate-400 font-bold uppercase tracking-wider text-[10px]">Coding Restriction:</span>
                        <span class="font-bold text-amber-700">${codingInfo.day} (${codingInfo.scheme})</span>
                    </div>
                </div>
                <p class="mt-3 text-[11px] text-slate-500 text-left">
                    Note: Driver must report to <b>TMO for Final Confirmation</b> to turn on GPS tracking and get final clearance.
                </p>
            `,
            icon: 'question',
            showCancelButton: true,
            confirmButtonColor: '#1D2542',
            cancelButtonColor: '#8A96BC',
            confirmButtonText: 'Yes, Release Franchise Number & Plate',
            cancelButtonText: 'Cancel'
        }).then((result) => {
            if (result.isConfirmed) {
                post(`/bplo/issue/${application.id}`, {
                    onSuccess: () => {
                        Swal.fire({
                            title: 'Franchise Released!',
                            text: `Sticker Number #${data.coding_scheme_number} and Franchise Number #${data.sticker_number} have been released. Unit advanced to TMO Final Confirmation.`,
                            icon: 'success',
                            confirmButtonColor: '#059669',
                            timer: 2500,
                            showConfirmButton: false
                        });
                    }
                });
            }
        });
    };

    return (
        <BPLOLayout title="Final Issuance" role="BPLO Officer">
            <Head title={`Finalize Release | ${application.reference || application.id} - TRIVORA`} />

            <div className="mx-auto max-w-7xl space-y-6 pb-12">

                {/* ══════════════════════════════════════════════════════════════
                    1. TOP NAVIGATION BAR
                   ══════════════════════════════════════════════════════════════ */}
                <div className="flex flex-wrap items-center justify-between gap-3">
                    <Link
                        href="/bplo/releasing"
                        className="group inline-flex items-center gap-1.5 text-xs sm:text-sm font-semibold text-slate-500 hover:text-slate-900 transition-colors"
                    >
                        <ChevronLeft size={16} strokeWidth={2.5} className="text-slate-400 group-hover:text-slate-700 transition-colors" />
                        <span>Back to Releasing Queue</span>
                    </Link>

                    <div className="flex items-center gap-2">
                        {application.reference && (
                            <span className="inline-flex items-center gap-1 rounded-lg border border-slate-200 bg-white px-2.5 py-1 text-xs font-mono font-bold text-[#1D2542] shadow-2xs">
                                {application.reference}
                            </span>
                        )}
                    </div>
                </div>

                {/* ══════════════════════════════════════════════════════════════
                    2. CLEAN PAGE HEADER (Consistent with TMO Standard)
                   ══════════════════════════════════════════════════════════════ */}
                <div className="border-b border-slate-200/80 pb-5">
                    <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-3">
                        <div>
                            <div className="text-[11px] font-bold uppercase tracking-wider text-slate-400">
                                BPLO Franchise Operations
                            </div>
                            <h1 className="mt-0.5 text-2xl sm:text-[28px] font-extrabold tracking-tight text-slate-900 leading-tight">
                                Sticker Number &amp; Franchise Number Release
                            </h1>
                            <p className="mt-1 text-xs sm:text-sm text-slate-500 max-w-2xl leading-relaxed">
                                Assign the official Sticker Number, verify the cashier receipt, and release the Franchise Number for municipal coding compliance.
                            </p>
                        </div>

                        <span className="inline-flex items-center gap-1.5 self-start sm:self-center px-3 py-1 rounded-full text-xs font-bold bg-indigo-50 text-[#1D2542] border border-indigo-200/80 shadow-2xs shrink-0">
                            <Bike size={13} strokeWidth={2.2} />
                            <span>Ready for Plate Issuance</span>
                        </span>
                    </div>
                </div>

                {/* ══════════════════════════════════════════════════════════════
                    3. TWO-COLUMN WORKSTATION (Dossier Left, Terminal Right)
                   ══════════════════════════════════════════════════════════════ */}
                <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 items-start">

                    {/* ── LEFT COLUMN: APPLICANT & CLEARANCE SUMMARY (5 cols) ── */}
                    <div className="space-y-6 lg:col-span-5">

                        {/* Card 1: Applicant & Tricycle Dossier */}
                        <div className={`overflow-hidden rounded-2xl border border-slate-200/70 bg-white ${CARD_SHADOW}`}>
                            <div className="flex items-center justify-between border-b border-slate-100 bg-slate-50/75 px-5 py-3.5">
                                <div className="flex items-center gap-2">
                                    <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-to-br from-[#1D2542]/[0.10] to-[#1D2542]/[0.02] text-[#1D2542]">
                                        <User size={15} strokeWidth={2.2} />
                                    </div>
                                    <h3 className="text-xs font-bold uppercase tracking-wider text-slate-700">
                                        Applicant &amp; Tricycle Information
                                    </h3>
                                </div>
                                <span className="text-[11px] font-semibold text-slate-400 font-mono">
                                    #{application.id}
                                </span>
                            </div>

                            <div className="p-5 divide-y divide-slate-100 text-xs">
                                {/* Tricycle Owner — primary applicant/owner, never the driver */}
                                <div className="pb-3.5 flex items-start justify-between gap-3">
                                    <div>
                                        <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 block">Tricycle Owner</span>
                                        <span className="text-sm font-bold text-slate-900 mt-0.5 block">{application.operator || '—'}</span>
                                    </div>
                                    <div className="h-8 w-8 rounded-full bg-gradient-to-br from-[#1D2542] to-[#2A3560] text-white flex items-center justify-center text-xs font-bold shadow-2xs shrink-0">
                                        {application.operator ? application.operator.charAt(0).toUpperCase() : 'O'}
                                    </div>
                                </div>

                                {/* Tricycle Driver — distinct block; only a separate person when ownerIsDriver is false */}
                                <div className="py-3">
                                    <div className="flex items-center justify-between gap-2">
                                        <span className="text-slate-500 font-medium flex items-center gap-1.5">
                                            <User size={13} className="text-slate-400" />
                                            Tricycle Driver
                                        </span>
                                        <span className={`font-semibold text-right ${application.ownerIsDriver ? 'text-slate-600' : 'text-indigo-700'}`}>
                                            {application.ownerIsDriver
                                                ? 'Same as Tricycle Owner'
                                                : (application.tricycleDriver?.full_name || 'Not provided')}
                                        </span>
                                    </div>
                                    {!application.ownerIsDriver && application.tricycleDriver && (
                                        <div className="mt-2 space-y-1 rounded-lg border border-indigo-200/70 bg-indigo-50/60 px-3 py-2 text-[11px] text-slate-600">
                                            <p>Birthday: <strong className="text-slate-800">{application.tricycleDriver.birthday || '—'}</strong></p>
                                            <p>Mobile: <strong className="text-slate-800">{application.tricycleDriver.contact_number || '—'}</strong></p>
                                            <p>Barangay: <strong className="text-slate-800">{application.tricycleDriver.barangay || '—'}</strong></p>
                                        </div>
                                    )}
                                </div>

                                {/* Make & Model */}
                                <div className="py-3 flex items-center justify-between gap-2">
                                    <span className="text-slate-500 font-medium flex items-center gap-1.5">
                                        <Bike size={13} className="text-slate-400" />
                                        Make &amp; Model
                                    </span>
                                    <span className="font-semibold text-slate-800">{application.make || '—'}</span>
                                </div>

                                {/* Engine Number */}
                                <div className="py-3 flex items-center justify-between gap-2">
                                    <span className="text-slate-500 font-medium flex items-center gap-1.5">
                                        <Gauge size={13} className="text-slate-400" />
                                        Engine Serial
                                    </span>
                                    <span className="font-mono font-semibold text-slate-700 bg-slate-50 px-2 py-0.5 rounded border border-slate-100">
                                        {application.engine_number || 'N/A'}
                                    </span>
                                </div>

                                {/* Chassis Number */}
                                <div className="pt-3 flex items-center justify-between gap-2">
                                    <span className="text-slate-500 font-medium flex items-center gap-1.5">
                                        <Hash size={13} className="text-slate-400" />
                                        Chassis Serial
                                    </span>
                                    <span className="font-mono font-semibold text-slate-700 bg-slate-50 px-2 py-0.5 rounded border border-slate-100">
                                        {application.chassis_number || 'N/A'}
                                    </span>
                                </div>
                            </div>
                        </div>

                        {/* Card 2: Before-Release Notice — BPLO does not record, verify, or process
                            payment in this system. Payment happens entirely offline at the
                            Municipal Treasurer's Office; this is a manual, in-person check only. */}
                        <div className={`overflow-hidden rounded-2xl border border-amber-200/80 bg-amber-50/40 ${CARD_SHADOW}`}>
                            <div className="flex items-center gap-2 border-b border-amber-100 bg-amber-50/60 px-5 py-3.5">
                                <div className="flex h-7 w-7 items-center justify-center rounded-lg bg-gradient-to-br from-amber-500/[0.16] to-amber-500/[0.02] text-amber-700">
                                    <AlertCircle size={15} strokeWidth={2.2} />
                                </div>
                                <h3 className="text-xs font-bold uppercase tracking-wider text-amber-800">
                                    Before You Release
                                </h3>
                            </div>

                            <div className="p-5 text-xs leading-relaxed text-slate-700">
                                Verify the applicant's TMO ticket and confirm that the required payment receipt has been presented before releasing the sticker and plate for coding.
                            </div>
                        </div>

                        {/* Card 3: Handover Notice to TMO */}
                        <div className="rounded-2xl border border-amber-200 bg-amber-50/60 p-4 shadow-2xs flex items-start gap-3.5">
                            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-gradient-to-br from-amber-500/[0.14] to-amber-500/[0.03] text-amber-600 shrink-0 mt-0.5">
                                <Info size={18} strokeWidth={2.2} />
                            </div>
                            <div className="min-w-0">
                                <h4 className="text-xs font-bold uppercase tracking-wider text-amber-900">
                                    Next Step: Final Confirmation at TMO
                                </h4>
                                <p className="mt-1 text-xs text-amber-800 leading-relaxed font-medium">
                                    BPLO releases the Franchise Number and coding plate. <strong>BPLO does not install GPS devices.</strong> After releasing the Franchise Number and plate, tell the driver to go to <strong>TMO for Final Confirmation</strong> to turn on GPS tracking.
                                </p>
                            </div>
                        </div>

                    </div>

                    {/* ── RIGHT COLUMN: ISSUANCE TERMINAL (7 cols) ── */}
                    <div className="space-y-6 lg:col-span-7">

                        <div className={`overflow-hidden rounded-2xl border border-slate-200/70 bg-white ${CARD_SHADOW}`}>
                            <div className="p-6 sm:p-7 space-y-6">

                                {/* Terminal Header */}
                                <div className="flex items-center justify-between border-b border-slate-100 pb-4">
                                    <div className="flex items-center gap-2.5">
                                        <div className="flex h-9 w-9 items-center justify-center rounded-xl bg-gradient-to-br from-[#1D2542]/[0.10] to-[#1D2542]/[0.02] text-[#1D2542] shadow-2xs">
                                            <Hash size={18} strokeWidth={2.4} />
                                        </div>
                                        <div>
                                            <h3 className="text-base font-bold text-slate-900">
                                                Sticker Number &amp; Franchise Number Assignment
                                            </h3>
                                            <p className="text-xs text-slate-400">
                                                Nasugbu Municipal Licensing Ordinance &bull; Final Step
                                            </p>
                                        </div>
                                    </div>
                                    <span className="hidden sm:inline-flex rounded-md bg-slate-100 px-2.5 py-1 text-[11px] font-mono font-bold text-slate-600">
                                        LGU-NASUGBU
                                    </span>
                                </div>

                                {/* ── AUTHENTIC MUNICIPAL PLATE SHOWCASE BOX ── */}
                                <div className="space-y-2">
                                    <div className="flex items-center justify-between text-xs">
                                        <span className="font-bold text-slate-700 flex items-center gap-1.5">
                                            <Lock size={12} className="text-slate-400" />
                                            Assigned Sticker Number Plate
                                        </span>
                                        <span className="text-[11px] text-slate-400 font-medium">
                                            Sequence Guaranteed Non-collision
                                        </span>
                                    </div>

                                    {/* Embossed Plate Card */}
                                    <div className="relative rounded-2xl border-2 border-slate-300 bg-gradient-to-b from-slate-50 via-white to-slate-100 p-6 sm:p-7 shadow-xs text-center overflow-hidden">
                                        {/* Four corner faux bolts */}
                                        <span className="absolute top-3 left-3 h-2 w-2 rounded-full border border-slate-400 bg-slate-300 shadow-inner" />
                                        <span className="absolute top-3 right-3 h-2 w-2 rounded-full border border-slate-400 bg-slate-300 shadow-inner" />
                                        <span className="absolute bottom-3 left-3 h-2 w-2 rounded-full border border-slate-400 bg-slate-300 shadow-inner" />
                                        <span className="absolute bottom-3 right-3 h-2 w-2 rounded-full border border-slate-400 bg-slate-300 shadow-inner" />

                                        {/* Top Header on Plate */}
                                        <div className="text-[10px] sm:text-[11px] font-extrabold uppercase tracking-widest text-slate-500">
                                            MUNICIPALITY OF NASUGBU &bull; BATANGAS
                                        </div>

                                        {/* Stamped Number */}
                                        <div className="my-2.5 sm:my-3">
                                            <span className="text-5xl sm:text-6xl font-black font-mono tracking-widest text-slate-900 select-all drop-shadow-2xs">
                                                {data.coding_scheme_number}
                                            </span>
                                        </div>

                                        {/* Plate Bottom Metadata Bar */}
                                        <div className="flex flex-wrap items-center justify-between gap-2 pt-3 border-t border-slate-200/80 text-[11px] font-semibold text-slate-500">
                                            <span className="uppercase tracking-wider text-[10px] text-slate-400">Tricycle for Hire</span>
                                            
                                            {/* Dynamic Coding Badge */}
                                            <span className={`inline-flex items-center gap-1.5 rounded-full px-2.5 py-0.5 text-[10.5px] font-bold border shadow-2xs ${codingInfo.badgeClass}`}>
                                                <span>{codingInfo.day} Coding ({codingInfo.scheme})</span>
                                            </span>
                                        </div>
                                    </div>

                                    <p className="text-[11px] text-slate-400 text-center leading-relaxed pt-1">
                                        This Sticker Number is automatically assigned from the municipal sequence to prevent duplication in the municipal registry.
                                    </p>
                                </div>

                                {/* ── FRANCHISE NUMBER FORM DISPLAY ── */}
                                <div className="space-y-1.5 pt-2">
                                    <label htmlFor="sticker_number" className="flex items-center justify-between text-xs font-bold text-slate-700">
                                        <span className="flex items-center gap-1.5">
                                            <ShieldCheck size={14} className="text-emerald-600" />
                                            <span>Franchise Number</span>
                                        </span>
                                        <span className="inline-flex items-center gap-1 text-[11px] font-semibold text-emerald-700 bg-emerald-50 px-2 py-0.5 rounded-full border border-emerald-200/80">
                                            <CheckCircle2 size={11} />
                                            Auto-Generated &amp; Persisted
                                        </span>
                                    </label>

                                    <div className="relative">
                                        <input
                                            type="text"
                                            id="sticker_number"
                                            value={data.sticker_number}
                                            readOnly
                                            className="w-full rounded-xl border border-slate-200 bg-slate-100 px-3.5 py-2.5 font-mono text-sm font-bold text-slate-700 shadow-2xs cursor-not-allowed uppercase select-all"
                                        />
                                        <Lock size={14} className="absolute right-3.5 top-1/2 -translate-y-1/2 text-slate-400" />
                                    </div>
                                    <p className="text-[11px] text-slate-400">
                                        The unique Franchise Number issued and registered to this application.
                                    </p>

                                    {errors.sticker_number && (
                                        <p className="text-[11px] font-medium text-rose-600 flex items-center gap-1 mt-1">
                                            <AlertCircle size={12} />
                                            {errors.sticker_number}
                                        </p>
                                    )}
                                </div>

                                {/* ── ACTION BUTTONS ── */}
                                <div className="pt-4 border-t border-slate-100">
                                    <button
                                        type="button"
                                        onClick={handleFinalize}
                                        disabled={processing}
                                        className="w-full inline-flex items-center justify-center gap-2 rounded-xl bg-[#1D2542] px-6 py-2.5 text-xs font-bold text-white hover:bg-[#2A3B5C] shadow-sm active:scale-[0.98] transition-all disabled:opacity-50"
                                    >
                                        {processing ? (
                                            <>
                                                <Loader2 size={15} className="animate-spin" />
                                                <span>Releasing Franchise...</span>
                                            </>
                                        ) : (
                                            <>
                                                <ShieldCheck size={15} strokeWidth={2.2} />
                                                <span>Release Franchise Number &amp; Plate</span>
                                            </>
                                        )}
                                    </button>
                                </div>

                            </div>
                        </div>

                    </div>

                </div>

            </div>
        </BPLOLayout>
    );
}