#!/bin/sh
set -e

echo "🚀 Booting Trivora on Render..."

# Create all necessary storage directories
mkdir -p /var/www/html/storage/framework/sessions \
         /var/www/html/storage/framework/views \
         /var/www/html/storage/framework/cache \
         /var/www/html/storage/logs \
         /var/www/html/bootstrap/cache

touch /var/www/html/storage/logs/laravel.log

# Ensure www-data full read/write permissions
chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache

# Clear stale caches
php artisan config:clear || true
php artisan cache:clear || true

# Run base schema if migrations table does not exist yet in TiDB
echo "🔄 Checking and initializing database schema on TiDB Cloud..."
php -r "
require 'vendor/autoload.php';
\$app = require_once 'bootstrap/app.php';
\$kernel = \$app->make(Illuminate\Contracts\Console\Kernel::class);
\$kernel->bootstrap();
try {
    if (!\Illuminate\Support\Facades\Schema::hasTable('migrations')) {
        echo 'Loading mysql-schema.sql into TiDB Cloud... ';
        if (file_exists('database/schema/mysql-schema.sql')) {
            \$schema = file_get_contents('database/schema/mysql-schema.sql');
            \Illuminate\Support\Facades\DB::unprepared(\$schema);
            echo 'Done.\n';
        } else {
            echo 'mysql-schema.sql not found.\n';
        }
    } else {
        echo 'Migrations table already exists.\n';
    }
} catch (\Throwable \$e) {
    echo 'Schema check notice: ' . \$e->getMessage() . '\n';
}
" || true

# Run database migrations
echo "🔄 Checking and running database migrations..."
php artisan migrate --force || true

# Seed database with all demo accounts (TMO, BPLO, Driver, Passenger, TODA zones, tricycles)
echo "🌱 Seeding database..."
php artisan db:seed --force || true

# Cache configurations and routes
echo "⚡ Optimizing application..."
php artisan config:cache || true
php artisan route:cache || true
php artisan view:cache || true

# Ensure storage link exists
php artisan storage:link || true

# Final permission fix to ensure www-data owns any files generated by artisan
chown -R www-data:www-data /var/www/html/storage /var/www/html/bootstrap/cache
chmod -R 777 /var/www/html/storage /var/www/html/bootstrap/cache

# Start PHP-FPM in background
echo "🔌 Starting PHP-FPM..."
php-fpm -D

# Start Nginx in foreground
echo "🌐 Starting Nginx Web Server on port 80..."
exec nginx -g "daemon off;"
