<?php

namespace App\Http\Controllers\Operator;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Inertia\Inertia;
use App\Models\Payment;
use App\Models\Tricycle;

class PaymentController extends Controller
{
    /**
     * Display payments list.
     */
    public function index(Request $request)
    {
        $user = $request->user();
        $operator = $user->operator;

        if (!$operator) {
            return Inertia::render('Operator/Payments/PaymentHistory', [
                'payments' => [],
            ]);
        }

        // Fetch payments linked to applications of this operator
        $payments = Payment::whereHas('application', function ($q) use ($operator) {
            $q->where('operator_id', $operator->id);
        })
            ->with(['application.tricycle'])
            ->orderByDesc('payment_date')
            ->get()
            ->map(function ($p) {
                return [
                    'id'          => 'TXN-2026-' . str_pad($p->id, 5, '0', STR_PAD_LEFT),
                    'db_id'       => $p->id,
                    'reference'   => $p->official_receipt_number ?: 'OR-PENDING',
                    'date'        => $p->payment_date ? $p->payment_date->format('M d, Y') : $p->created_at->format('M d, Y'),
                    'method'      => ucwords($p->payment_method),
                    'unit'        => $p->application->tricycle?->body_number ?: 'Pending',
                    'amount'      => (float)$p->amount,
                    'status'      => $p->is_verified ? 'completed' : 'pending',
                ];
            });

        return Inertia::render('Operator/Payments/PaymentHistory', [
            'payments' => $payments,
        ]);
    }

    /**
     * Display single payment receipt.
     */
    public function receipt(Request $request, $id)
    {
        $user = $request->user();
        $operator = $user->operator;

        if (!$operator) {
            abort(403);
        }

        $p = Payment::where('id', $id)
            ->with(['application.tricycle.todaZone'])
            ->firstOrFail();

        $receiptData = [
            'id'          => 'TXN-2026-' . str_pad($p->id, 5, '0', STR_PAD_LEFT),
            'db_id'       => $p->id,
            'or_number'   => $p->official_receipt_number ?: 'OR-PENDING',
            'date'        => $p->payment_date ? $p->payment_date->format('M d, Y') : $p->created_at->format('M d, Y'),
            'time'        => $p->payment_time ?: $p->created_at->format('h:i A'),
            'method'      => ucwords($p->payment_method),
            'unit'        => $p->application->tricycle?->body_number ?: 'Pending',
            'plate_no'    => $p->application->tricycle?->plate_number ?: 'N/A',
            'operator'    => $operator->full_name,
            'amount'      => (float)$p->amount,
            'status'      => $p->is_verified ? 'verified' : 'pending',
            'notes'       => $p->notes ?: 'Official Receipt generated by cashier.',
        ];

        return Inertia::render('Operator/Payments/Receipt', [
            'receipt' => $receiptData,
        ]);
    }
}
